[default]
# default environment settings
NAME = "apt"
REDIS_PREFIX = "apt"
VALIDATOR_CURRENCY = "apt"
KEY_ID = "aptos"
# default network settings
MAX_GAS_AMOUNT = 3000
SIGNING_ALGORITHM = "aptos.Ed25519"
TRANSACTION_EXPIRE_TIME = 600
HD_PATH = "m/44/637/0/0/"
PRECISION = 8

[debug]
DEBUG = true
HOSTNAME = "127.0.0.1"
PORT = 6071


[prod]
DEBUG = false
HOSTNAME = "aptos6"
PORT = 6070

[vip]
DEBUG = false
HOSTNAME = "aptos6"
PORT = 6070

[default.networks.testnet]
NETWORK="testnet"
NODE_URL = "https://fullnode.testnet.aptoslabs.com/v1"

[default.networks.mainnet]
NETWORK="mainnet"
NODE_URL = "https://fullnode.mainnet.aptoslabs.com/v1"
